---
name: Myers
author: Posthaven
url: https//posthaven.com/
posts_per_page:
  include_in_settings: true
  default: 5
settings:
- id: link-color
  label: Link color
  type: color
  default: "#D88D14"
- id: color-scheme
  label: Color scheme
  type: radio
  default: light
  options:
  - value: auto
    label: Auto (matches browser preference)
  - value: light
    label: Light background
  - value: dark
    label: Dark background
- id: social-links
  label: Show social share buttons
  default: true
  type: checkbox